# Assignment 2 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [44]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [45]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [46]:
#Your code starts here 

file_count=0
files_dict={}

name = 'f*.txt'     #since we have the file1,2,3 with extension txt which contain data
#file_path=input("Enter the file path where you have files containing data ? ")
#file_path = 'D:\\5th semester\\ML\\Assignmnet 2 - IRS\\files'
files = os.listdir('.')        #it will contain the all files which are in the specified path 
for i in files:  
    if  fnmatch.fnmatch(i, name) :    #it will check the files having f as their first word and .txt extension
        file_count=file_count+1;              #if found it will add 1 in variable
        #print(i)
        #files_dict[file_count] = i      # it will  create dictionary having key values (i =file name) and items (files count 1,2,3)
        files_dict[i] = 0               #it will  create dictionary having items (i =file name of only which is True (f*.txt)) and key values =0
print("\nTotal Number  of files\n", file_count)
print("\nDictionary containing  files\n", files_dict)


Total Number  of files
 3

Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 0, 'f3.txt': 0}


Displaying the count of files.

In [47]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [48]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 0, 'f3.txt': 0}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [49]:
#Your code starts here    
unique_word_set = set()         #declaring a set for unique words
#files_dict = {'f1.txt': 0, 'f2.txt': 0,'f3.txt' :0}
for i  in files_dict :    #iterating through files_dict which have f1,f2,f3
    fhand=open (i)         #it will open the file
 
    for line in fhand:      
        words = line.split()       #it will separate  words of each line as list
        for word in words:          #iterate each word in list 
            lower = word.lower()       # as in file caps aslo user like This or this to consider both as same we are converting in lower alphabets  
            if lower not in unique_word_set:   #since no word should come twice in set as it is unique so checking if it isn't already in set
              unique_word_set.add(lower)      #if not already there add it
                



           
print (unique_word_set)
print("\nCount of files  ", file_count)
#Your code ends here

{'interesting', 'is', 'my', 'pen', 'book', 'this'}

Count of files   3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

- Create Term doc matrix such that colmns will be unique words and all the files will be rows
- Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [50]:
#Your code starts here    
import numpy

i=0
j=0
dict_uwords={}             #to have dictionary of unique words
doc_matrix = numpy.full((file_count,len(unique_word_set)), 0)    #it will create matrix haing rows equal to files no (3) column = no of unique words
print(doc_matrix)
for item in unique_word_set :       #iterating through each unique word from set
    dict_uwords[item]=i             #then adding that word as key in dict_uwords and value of that (each) key
    i=i+1                            #is incrementing by 1 (as we need unique ids)
for file in files_dict :            #iterating through each file from file_dict
    files_dict[file]=j              #giving each file (key) a value of i 
    j=j+1                           #j is  incrementing by 1 (as we need unique ids)

print(dict_uwords) 
print("Dictionary of files")
print(files_dict)  
    
#Your code ends here 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
{'interesting': 0, 'is': 1, 'my': 2, 'pen': 3, 'book': 4, 'this': 5}
Dictionary of files
{'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

- Fill the term doc matrix by checking if the unique word exists in a file or not
- If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
- Do the same for all the files present in the directory

In [51]:
#Your code starts here   
i=0 
for i,file in enumerate(files_dict):  #iterating through file_dict by using this built-in function as this will give two things index ,0,1,2 and keys of dict
    fhand= open(file,'r')              #opening file in read mode
    words = fhand.read().lower().split()    #again this will read lines and convert into lower so that This and this type scenario can be dealt 
                                           #this will create list for each file seprating each word as['this', 'is', 'my', 'book]
     # print(words) 
    for j,word in enumerate(dict_uwords) :  #iterating through dict of unique words by using =built-in function as this will give two things index ,0,1,2 and keys of dict
        if word in words:                   #checking if the word in unique word set is in file 
            doc_matrix[i, j] = 1            #if yes then TERM_DOC_MATRIX[file][word] = 1 here i is  index of file and j is index of unqiue word 
print("Dictionary of unique words")   
print(dict_uwords)
print("\nTerm Matrix Document")
print(doc_matrix)

#Your code ends here

Dictionary of unique words
{'interesting': 0, 'is': 1, 'my': 2, 'pen': 3, 'book': 4, 'this': 5}

Term Matrix Document
[[0 1 1 0 1 1]
 [0 1 1 1 0 1]
 [1 1 1 0 1 0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [52]:
#Your code starts here    
import numpy

query_vector=numpy.full((len(dict_uwords),1), 0)  #creating a matrix having rows no = to no of unique words 1 column and filling it with zero
print("colVector Initially ")
print(query_vector)
#print(words)

#Your code ends here

colVector Initially 
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]]


'for j,word in enumerate(dict_uwords):\n            # Check if the word is in the file\n        if word in words:\n            query_vector[0, j] = 1\nprint(query_vector)'

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [53]:
query = input("\nWrite something for searching  ")
print(query)
# Check every word of query if it exists in the set of unique words or not

# If exists then increment the count of that word in word dictionary


book reading  is my favourite hobby . This is good


In [54]:
#Your code starts here   
import numpy
words=query.split()                #spliting the query as a list so that we can deal it as separate word
query_vector=numpy.full((len(dict_uwords),1), 0)  #creating a matrix having rows no = to no of unique words and 1 column and filling it with zero
for word in words:         #iterating each word of query        
        if word in dict_uwords:     #checing if word in query is also in unique words dictionary
            #print(word)
            #print(j)
            query_vector[dict_uwords[word],0]=query_vector[dict_uwords[word],0]+1  #if yes the 0 column and row (which is representing the unique id of that unique word) add 1 into it each time we find that word
print("Col Vector after query ")
print(query_vector)
#Your code ends here

Col Vector after query 
[[0]
 [2]
 [1]
 [0]
 [1]
 [0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [57]:
#Your code starts here  
resultant_vec=numpy.full((file_count,1),0)  #creating a matrix having rows no = to no of files and 1 colum
max_v=0
resultant_vec=doc_matrix.dot(query_vector)   # multiplying the two matrix the query one and doc (representing words in files) to check the max of matching words we are having
print("Result " , resultant_vec)
for i in resultant_vec :  # itering rows of resultant matrix
    #print(i)
    for j in i :   # itering all columns values of rows (00,01,02,03...10,11,) of resultant matrix
        #print(j)
        if j>max_v :   #checking if column value is large then stroing it in max
            max_v=j
            max_index=numpy.argmax(resultant_vec)    #built in function to find the index having max value 
print("max index\n ", max_index)
print("max\n ", max_v)

#Your code ends here

Result  [[4]
 [3]
 [4]]
max index
  0
max
  4


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [56]:
#Your code starts here 
c = -1  

for file in files_dict: #iterating through all files in file dict 
    c += 1              #incrementing c to keep index of file
    if c == max_index:  # if c reaches the max  index (found above)
        fhand =open(file, 'r')  # open file in read mode
        for line in fhand:   #read lines
            print(line)

#Your code ends here

This is my book


Congratulations Now you are able to build your own small IRS.