# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [2]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [3]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [4]:
#Your code starts here   
file_count=0
files_dict={}

name = 'f*.txt'     #since I have  created the file1,2,3 with extension txt which contain data so for specification of file type i write this
#file_path=input("Enter the file path where you have files containing data ? ")
#file_path = 'D:\\5th semester\\ML\\Assignmnet 2 - IRS\\files'
files = os.listdir('.')           #it will contain the all files which are in the current directory   
for i in files:                     #iterating all the files
    if  fnmatch.fnmatch(i, name) :    #it will check the files having f as their first word and .txt extension
        file_count=file_count+1;              #if found it will add 1 in variable
        #print(i)
        #files_dict[file_count] = i      # it will  create dictionary having key values (i =file name) and items (files count 1,2,3)
        files_dict[i] = 0               #it will  create dictionary having items (keys) (i =file name of only which is True (f*.txt)) and  values =0
print("\nTotal Number  of files\n", file_count)
print("\nDictionary containing  files\n", files_dict)
#Your code ends here       


Total Number  of files
 3

Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 0, 'f3.txt': 0}


Displaying the count of files.

In [5]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [6]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 0, 'f3.txt': 0}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [7]:
#Your code starts here    
unique_word_set = set()         #declaring a set for unique words
#files_dict = {'f1.txt': 0, 'f2.txt': 0,'f3.txt' :0}
for i  in files_dict :    #iterating through files_dict which have f1,f2,f3
    fhand=open (i)         #it will open the file
    for line in fhand:      
        words = line.split()       #it will separate  words of each line as list
        for word in words:          #iterate each word in list 
            lower = word.lower()       # as in file caps aslo user like This or this to consider both as same we are converting in lower alphabets  
            if lower not in unique_word_set:   #since no word should come twice in set as it is unique so checking if it isn't already in set
              unique_word_set.add(lower)      #if not already there add it
                
           
print (unique_word_set)
print("\nCount of files  ", file_count)
#Your code ends here

{'pen', 'is', 'book', 'this', 'interesting', 'my'}

Count of files   3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [8]:
#Your code starts here
#Your code starts here    
import numpy

i=0
j=0
dict_uwords={}             #to have dictionary of unique words
doc_matrix = numpy.full((file_count,len(unique_word_set)), 0)    #it will create matrix haing rows equal to files no (3) column = no of unique words
print(doc_matrix)
for item in unique_word_set :       #iterating through each unique word from set
    dict_uwords[item]=i             #then adding that word as key in dict_uwords and value of that (each) key
    i=i+1                            #is incrementing by 1 (as we need unique ids)
for file in files_dict :            #iterating through each file from file_dict
    files_dict[file]=j              #giving each file (key) a value of i 
    j=j+1                           #j is  incrementing by 1 (as we need unique ids)

print(dict_uwords) 
print("Dictionary of files")
print(files_dict)  
    
#Your code ends here

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
{'pen': 0, 'is': 1, 'book': 2, 'this': 3, 'interesting': 4, 'my': 5}
Dictionary of files
{'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [9]:
#Your code starts here   
i=0 
for i,file in enumerate(files_dict):  #iterating through file_dict by using this built-in function as this will give two things index ,0,1,2 and keys of dict
    fhand= open(file,'r')              #opening file in read mode
    words = fhand.read().lower().split()    #again this will read lines and convert into lower so that This and this type scenario can be dealt 
                                           #this will create list for each file seprating each word as['this', 'is', 'my', 'book]
     # print(words) 
    for j,word in enumerate(dict_uwords) :  #iterating through dict of unique words by using =built-in function as this will give two things index ,0,1,2 and keys of dict
        if word in words:                   #checking if the word in unique word set is in file 
            doc_matrix[i, j] = 1            #if yes then TERM_DOC_MATRIX[file][word] = 1 here i is  index of file and j is index of unqiue word 
print("Dictionary of unique words")   
print(dict_uwords)
print("\nTerm Matrix Document")
print(doc_matrix)

#Your code ends here

Dictionary of unique words
{'pen': 0, 'is': 1, 'book': 2, 'this': 3, 'interesting': 4, 'my': 5}

Term Matrix Document
[[0 1 1 1 0 1]
 [1 1 0 1 0 1]
 [0 1 1 0 1 1]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [10]:
#Your code starts here    

import numpy
query_vector=numpy.full((len(dict_uwords),1), 0)  #creating a matrix having rows no = to no of unique words and filling it with zero
print("colVector Initially ")
print(query_vector)

#Your code ends here

colVector Initially 
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [11]:
query = input("\nWrite something for searching:  ")
print("Query is:", query)

Query is: this is a fascinating publication written with a ballpoint


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [12]:
#your code starts here
synonym_file_path = r"files\synonyms.txt"
fhand =open('synonyms.txt')
synonyms_dict = {}

for lines in fhand :     #iterating through each line of file 
    k=lines.split(':')   #spliting the line in two parts in list by using : as separator this will separate the key word and the list of synonyms words 
    
    for i in range(len(k)-1): #this will iterate the list as list has 2 parts mean size=2 so i did len(k)-1 because i just want to iterate 0,1 index
        key=k[i]            #this will store the 1st element(before colon ) of list in key variable 
        val=k[i+1].strip().split((', '))    #this will store the 2nd element(after colon ) of list in val list as we are spliting either by ,
                                            #space since 1st three rows in file  in expected output , is not dealt as separator but in other ,space
        
        synonyms_dict[key]=val


print(synonyms_dict)   

#commenting this becz first i thought that we are supposed to take word from user and  show all its synonyms like a:b,c,d if user say b so we have to show b:a,c,d
'''word=query.split()
synonyms_dict = {} # dictionary to store synonyms
for lines in fhand :
    word_line=lines
    
   # print(word_line)
    for word1 in word:
       # print(word1)
           if word1 in word_line :
             if word1 in  lines :
                if word1 not in synonyms_dict:
                    synonyms_dict[word1] = []
                    
                       
                    synonyms_dict[word1].append(word_line)

#your code ends here

print("\nSynonyms Dictionary\n")
print(synonyms_dict)'''

{'write': ['compose,draft,author,create'], 'file': ['document,record,dossier,report'], 'example': ['illustration,instance,sample,demonstration'], 'query': ['question', 'inquiry', 'search', 'request'], 'synonym': ['equivalent', 'substitute', 'alternate', 'replacement'], 'retrieve': ['fetch', 'recover', 'obtain', 'bring back'], 'system': ['framework', 'structure', 'organization', 'arrangement'], 'search': ['seek', 'look for', 'explore', 'examine'], 'lost': ['misplaced', 'missing', 'forgotten', 'mislaid'], 'pen': ['write', 'ink', 'ballpoint', 'fountain'], 'paper': ['document', 'sheet', 'form', 'letter'], 'book': ['novel', 'volume', 'publication', 'tome'], 'read': ['peruse', 'scan', 'study', 'look at'], 'interesting': ['fascinating', 'engaging', 'intriguing', 'absorbing'], 'computer': ['machine', 'device', 'processor', 'laptop'], 'software': ['program', 'application', 'app', 'platform']}


'word=query.split()\nsynonyms_dict = {} # dictionary to store synonyms\nfor lines in fhand :\n    word_line=lines\n    \n   # print(word_line)\n    for word1 in word:\n       # print(word1)\n           if word1 in word_line :\n             if word1 in  lines :\n                if word1 not in synonyms_dict:\n                    synonyms_dict[word1] = []\n                    \n                       \n                    synonyms_dict[word1].append(word_line)\n\n#your code ends here\n\nprint("\nSynonyms Dictionary\n")\nprint(synonyms_dict)'

### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [13]:
expanded_query = []
# Write code to expand the query using synonyms
#your code starts here

expanded_query=query.split()  #using split to separate the words of query 
for index,part in enumerate(expanded_query):  # as we have to insertv synonym words in query so we need index that why using this built func part will contain words of query
    for i in synonyms_dict:    #iterating thorugh the sysnonyms dictionary 
        ans=synonyms_dict[i]   #storing the values of each key (word )in dic as ans list
        if part in ans :        #if query word is in the list of words (synonyms) values o key in dic of synonyms
            expanded_query.insert((index+1),i)   #the in the next index of that query word add the key word 


#your code ends here

print("Expanded Query")
print(expanded_query)

Expanded Query
['this', 'is', 'a', 'fascinating', 'interesting', 'publication', 'book', 'written', 'with', 'a', 'ballpoint', 'pen']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [14]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary


In [15]:
#Your code starts here   
import numpy
words=expanded_query               #spliting the query as a list so that we can deal it as separate word
query_vector=numpy.full((len(dict_uwords),1), 0)  #creating a matrix having rows no = to no of unique words and 1 column and filling it with zero
for word in words:         #iterating each word of query        
        if word in dict_uwords:     #checing if word in query is also in unique words dictionary
            #print(word)
            #print(j)
            query_vector[dict_uwords[word],0]=query_vector[dict_uwords[word],0]+1  #if yes the 0 column and row (which is representing the unique id of that unique word) add 1 into it each time we find that word
print("Col Vector after query ")
print(query_vector)
#Your code ends here

Col Vector after query 
[[1]
 [1]
 [1]
 [1]
 [1]
 [0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [16]:
#Your code starts here  
#Your code starts here  
resultant_vec=numpy.full((file_count,1),0)  #creating a matrix having rows no = to no of files and 1 colum
max_v=0
resultant_vec=doc_matrix.dot(query_vector)   # multiplying the two matrix the query one and doc (representing words in files) to check the max of matching words we are having
print("Result " , resultant_vec)
for i in resultant_vec :  # itering rows of resultant matrix
    #print(i)
    for j in i :   # itering all columns values of rows (00,01,02,03...10,11,) of resultant matrix
        #print(j)
        if j>max_v :   #checking if column value is large then stroing it in max
            max_v=j
            max_index=numpy.argmax(resultant_vec)    #built in function to find the index having max value 
print("max index\n ", max_index)
print("max\n ", max_v)

#Your code ends here
#Your code ends here

Result  [[3]
 [3]
 [3]]
max index
  0
max
  3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [17]:
#Your code starts here    
c = -1  

for file in files_dict:
    c += 1
    if c == max_index:  # Open the file when c reaches the desired index
        fhand =open(file, 'r')  # Use `with` for proper file closure
        for line in fhand:
            print(line)

#Your code ends here

This is my book


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.